### ISSUE TITLE
Bower files

### ISSUE THREAD

**Issue by silvioprog** [homerjam/angular-ui-router-anim-in-out#11]
Hello,

Firstly, thank for this very nice plugin! =)

So, I had some problem using it with Bower. It seems that its CSS isn't showed in the bower paths, then I can't use it properly with Gulp plugin [main-bower-files](https://www.npmjs.com/package/gulp-main-bower-files).

Just to show the bower files, peform this command:

```bash
$ bower list --paths
```

It will show the following result:

```bash
'angular-ui-router-anim-in-out': 'bower_components/angular-ui-router-anim-in-out/anim-in-out.js'
```

It would be nice if it could return the following result:

```bash
'angular-ui-router-anim-in-out': ['bower_components/angular-ui-router-anim-in-out/anim-in-out.js', 'bower_components/angular-ui-router-anim-in-out/css/anim-in-out.css']
```

Thank you!

**Comment by homerjam** [comment]
I think generally the `main` files are used when bundling js - I'm not sure its a good idea to pollute it with css. A better solution would be to compile your css in a separate build step or import via sass/less.

**Comment by silvioprog** [comment]
Bootstrap's package uses something like this on its bower.json: https://github.com/twbs/bootstrap/blob/master/bower.json#L17. =)

**Comment by homerjam** [comment]
Thats a fair point, but bootstrap is a css framework. If anything I would add the `.scss` file as they have added the `.less` file - but there are other trivial ways to add a file like that to a buildstep. If you create a PR with the `.scss` file included then we can open it up for a vote perhaps.
