### ISSUE TITLE
Publish on npm and prepare for browserify

### ISSUE THREAD

**Issue by apinnecke** [homerjam/angular-ui-router-anim-in-out#14]
Hi,

would you please publish this package to npm and prepare it for browserify? This may be helpful: http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

Thanks :)

**Comment by homerjam** [comment]
Please can you test `homerjam/angular-ui-router-anim-in-out#browserify`

**Comment by apinnecke** [comment]
Yep, looks fine. There's just one little thing. In ìndex.js` it needs to be
```js
module.exports = 'anim-in-out';
```

With that slim modification it works perfectly as expected. :+1:

**Comment by homerjam** [comment]
Cool, thats done

**Comment by apinnecke** [comment]
Thanks for quick support! :)
