### ISSUE TITLE
Slide synced animation pushes the exiting view down

### ISSUE THREAD

**Issue by tomeram** [homerjam/angular-ui-router-anim-in-out#17]
I looked on your demo site and the slide animation works since you are using position absolute... Maybe you should always use position absolute for synced transitions?

thanks!

**Comment by homerjam** [comment]
Yes this is a necessity. The way ui-router/ng-animate works is by adding both incoming and outgoing views to the dom. Therefore if positioned relatively the ui-view elements will effect each others position.
