### ISSUE TITLE
Transition issue. Both views are being displayed

### ISSUE THREAD

**Issue by 4tron** [homerjam/angular-ui-router-anim-in-out#20]
![issue](https://cloud.githubusercontent.com/assets/11210554/13729375/56837f9e-e93c-11e5-9d70-7d81f0554d19.gif)

**Comment by homerjam** [comment]
I've added an note about this [here](https://github.com/homerjam/angular-ui-router-anim-in-out#why-is-the-position-of-my-views-all-messed-up-or-why-are-both-views-visible-during-the-transition)

**Comment by ghost** [comment]
Cool. Thanks. Rad transitions btw. Nice addition to our routing stuff.
