### ISSUE TITLE
Possible to have the animation without absolute view?

### ISSUE THREAD

**Issue by mattiLeBlanc** [homerjam/angular-ui-router-anim-in-out#21]
Hi,

I am running into one issue where the absolute position of the ui-view that slides creates issues with the size of the parent element.
I have to set the absolute positioned element to a fixed height for it to work but that is causing issues because the view can grow (when form elements trigger errors, the error message slides out).
So I ideally I would work with a non fixed height but that conflicts with the absolute positioning.

Any suggestions?

**Comment by homerjam** [comment]
Hi,

Can you use `min-height` to solve this?

I'm afraid you are required to use absolute positioning on at least one of the the `ui-view` elements during the transition in order for them not to push each other around. There are animation classes applied during the transition that may help you to only have one view absolute positioned at a time, it will hinge on your timings though.

An example would help if you can post one?

**Comment by mattiLeBlanc** [comment]
I was afraid of that. I don't really have an easy example because it is part of the app we are building.
However, I think it must be possible to have to views next to each other during the transition as long as the parent can accomodate it. Together with some clear overflow I think I can pull it off. But I have no time for it now. So if I do have time, I will give it a try and update/share here.
