### ISSUE TITLE
The ui-view in SCSS

### ISSUE THREAD

**Issue by ymhuang0808** [homerjam/angular-ui-router-anim-in-out#22]
The `[ui-view]` with `position: absolute;` in [the scss file](https://github.com/homerjam/angular-ui-router-anim-in-out/blob/master/scss/anim-in-out.scss#L3) affects the layout. Could it be removed?

**Comment by homerjam** [comment]
I decided to insert this/turn on by default as it was the main cause of issues. As its virtually always required I will leave it in place. To negate this in your own project please use:

```
[ui-view] {
    position: relative !important;
}
```
