### ISSUE TITLE
Animation between views

### ISSUE THREAD

**Issue by fstodulski** [homerjam/angular-ui-router-anim-in-out#24]
What if i want to start animate on start but before view change? 
http://codepen.io/anon/pen/LxjBvY

That allow me to slide down each element on animation end, but i want to do this in reverse BUT before view change.

**Comment by homerjam** [comment]
Sorry I'm not sure I understand - maybe a sketch would help?

The codepen won't work for me either I'm afraid - it keeps refreshing?

**Comment by fstodulski** [comment]
I mean that i want to start an animate before change the view. 
Click on a ui-sref  => wait for animate completed => change the view

**Comment by homerjam** [comment]
This is already possible - you just need to delay the incoming view until the first animation is finished.
