### ISSUE TITLE
AnimOut not triggered in Angular v1.2.26

### ISSUE THREAD

**Issue by helloflow** [homerjam/angular-ui-router-anim-in-out#4]
Hi,

Great directive! 

I've run into a problem where 'animOut' is not triggered in my stateControllers. It does work with the angular version in this repo: v1.2.16, but it seems to be broken when working with v1.2.26. The 'animIn' is working in both versions though.

Can't figure out what seems to be the problem so far... Anybody has a fix for this?

Cheers!

**Comment by homerjam** [comment]
I've removed state controller events - use $rootScope events instead and match the element.
